version: 2
jobs:

  deploy:
    - run:
        name: Deploy Master to Heroku
        command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

  build:
    working_directory: ~/atomicmp-auth
    docker:
      - image: circleci/node:10.10.0
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-npm-deps
          command: npm install
      - run:
          name: test
          command: npm test

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master